### ISSUE TITLE
Nvidia version 396.54.09 support.

### ISSUE THREAD

**Issue by NolanSyKinsley** [smxi/sgfxi#27]
I have tried and tried but for the life of me SGFXI is the only way I can get nvidia drivers properly installed on my system, but I need the 396.54.09 beta driver for a specific patch that it currently has that the main branch and 410 branch does not, and it will help get quite a few games working under linux in Steam's Proton compatibility layer. I was wondering if there was a way I could get SGFXI to support installing the 396.54.09 NVIDIA driver branch.

**Comment by smxi** [comment]
Sounds reasonable, just update sgfxi with -U, then do: sgfxi -o 396.54.09 to force that driver install.

I'll just leave that driver with a note about why the legacy beta driver was left, usually I remove those from sgfxi after beta testing phase is done.

**Comment by NolanSyKinsley** [comment]
This worked for me... with a few fixes. SGFXI is looking to download the file from https://download.nvidia.com/XFree86/Linux-x86_64/396.54.09/NVIDIA-Linux-x86_64-396.54.09.run but it does not exist there, and browsing around does not exist in those files. Looking at the builds my system uses, it downloads it from https://developer.nvidia.com/linux-3965409 . So I downloaded it, placed it in /usr/src/sgfxi-downloads/ and proceeded with sgfxi -o 396.54.09 as normal which then proceeded without issue.

**Comment by smxi** [comment]
Oh, I should have checked the download url, however, that url is not usable inside of sgfxi, it doesn't work that way.

Basically nvidia is doing exactly what they should be doing, removing a beta driver once it's been pushed to current new stable, and you found an old download url that only points to that specific driver.

There used to be alternate download locations, I'll check to see, but I think while I would like to offer this, the fact may be that nvidia, correctly, removes all beta drivers once they are  out of beta state. 

A url must be a path plus the driver itself, otherwise sgfxi can't do it, it's all abstracted, it must be in that format.

**Comment by smxi** [comment]
I"m going to have to close this and remove that driver, there is no fix that I can see.

Note that your issue is actually an issue/bug you should file with nvidia, since you can clearly state why you need this feature of the driver, that was apparently removed.

https://devtalk.nvidia.com/default/topic/522835/linux/if-you-have-a-problem-please-read-this-first/

nvidia makes it very easy to file a bug report, probably the best of any major company out there.

You'll need to run their debugger on the driver that is not doing what you need, you could also run it on this current one first to be on the safe side, then submit both gz'ed debugger files when you file your nvidia report.

I'll have to roll this change back in sgfxi because it makes little sense to offer a driver that sgfxi can't download.
