### ISSUE TITLE
Issue with gcc detection with kernel 5.8

### ISSUE THREAD

**Issue by Neo2SHYAlien** [smxi/sgfxi#43]
There is changes in /proc/version and the script is unable to detect gcc version:
```
cat /proc/version
Linux version 5.8.0-0.slh.1-aptosid-amd64 (s.l-h@gmx.de) (gcc-10 (Debian 10.2.0-3) 10.2.0, GNU ld (GNU Binutils for Debian) 2.35) #1 SMP PREEMPT aptosid 5.8-1 (2020-08-03)
```
In oldest version /proc/version looks like:
```
cat /proc/version 
Linux version 4.19.0-9-amd64 (debian-kernel@lists.debian.org) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07)
```
So the detection get nothing as result:
`local gccVersion=$( grep -Eio 'gcc[[:space:]]*version[[:space:]]*[0-9]{1,2}\.[0-9]{1,2}' /proc/version | grep -Eo '[0-9]{1,2}\.[0-9]{1,2}' )`
Probably `gcc --version`  or `gcc -v` are better alternative ? This will require little bit more to find a gcc binary path but will be independent from future changes in /proc/version

**Comment by smxi** [comment]
Unfortunately gcc --version has nothing to do with the gcc version used to build the kernel, that would be delightlfully easy.

so it's just a matter of modifying the pattern to handle either case, or testing the old one, then the new one. That will probably work best since it won't touch the detection for legacy stuff.

**Comment by smxi** [comment]
Since this was a random change in /proc/version done for unknown reasons, and it's unknown if the syntax is the same in all kernels from all distros, which it probably is not, I'll need a few more samples from other kernels to know if the fix is adequate.

The first part is fine, I'm just retaining the old sensible and easy to parse and process 'gcc version' detection, which was of course replaced by a difficult to parse, and less clear new version. So to be more solid, I'll need to find more /proc/version strings from new kernels on for example debian, ubuntu, arch, rpm distro, to see if the patterns are the same.

**Comment by Neo2SHYAlien** [comment]
@smxi Slackware sample

`Linux version 5.8.0 (root@thinkpad.slackware.bg) (gcc (GCC) 9.3.0, GNU ld version 2.33.1-slack15) #1 SMP Wed Aug 5 13:07:00 EEST 2020`

**Comment by smxi** [comment]
This issue is handled in latest sgfxi. Note that I'm still doing some assumptions that other distros may not match, but the sgfxi userbase on non debian / buntu distros is tiny so that doesn't matter. Your sample did show me what to not assume however, so that was useful. Tested and seems to be working. Confirm it is, which it should be and I'll close this issue, thanks.

**Comment by smxi** [comment]
assuming I fixed it, since I ran the test strings and they worked.
