### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Emilio942** [smxi/sgfxi#70]
I started the program first and then I didn't work on the server and then I had to start it 

$ root
Xorg
$
 separately and then suddenly go to why does it suddenly work again?

**Comment by smxi** [comment]
This isn't a question, there's zero information supplied. I mean, yes, technically it's a question, but it's not a question anyone can answer.

Debian has a funny little factoid on their IRC:  

<< doesn't work is Look buddy, "doesn't work" is a vague statement.  Does it sit on the couch all day long?  Does it procrastinate doing the dishes?  Does it beg on the street for change?  Please be specific!  Define 'it' and what it isn't doing.  Give us more details so we can help you without needing to ask basic questions like "what's the error message".

However, basically I'm not super interested in spending time on random issues with no definition on sgfxi, that project is largley in maintenance mode only now, it does get updates because another guy is following nvidia drivers, so the drivers tend to be current, as do the driver tests, but otherwise it's largely as is.

If you were in X, of course it didn't work!! lol, it shouldn't even have let you start it, so that may be what you mean when you say it didn't work.

I suggest you use the server package manager to install the drivers and leave it alone since I don't think you really need to be trying to do this type of stuff.

**Comment by Emilio942** [comment]
was a right fix for that I didn't run it with root the problem was with that but I didn't allocate the path to Rechte so I could in Ruth it still gave me the 

error
Not root
Error

I got it  then finally solved that i

Fix
$
tree -p
$

To the file 
$
chmod 0777 
$
